
@port = {{$dotenv PORT}}
@hostname = {{$dotenv SERVER_HOST}}
@baseurl = {{hostname}}:{{port}}

### expected output HTTP/1.1 400 Bad Request {"error":"missing location parameter"}
GET http://localhost:3000/api/search?

### 
GET http://localhost:3000/api/search?location=PARIS

### 
GET http://{{baseurl}}/api/search?location=''

### 
GET http://{{baseurl}}/api/search/?location=LYON

###
GET http://{{baseurl}}/api/search/?location=LYON&filters=1

###
GET http://{{baseurl}}/api/search/?location=ETRETAT&filters=1&food

###
GET http://{{baseurl}}/api/search/?location=LYON&filters=1&pub=1


###
GET http://{{baseurl}}/api/search/?location=LYON&filters=1&pub=1&food=1

###
POST http://{{baseurl}}/api/activity/new
Content-Type: application/x-www-form-urlencoded

name='Plage'
&user_id=1
&travelogue_id=1
&information="blabla"
&location={ lat :42.42, lon=04.04 }

### 
GET http://{{baseurl}}/api/mes-voyages/1


### 
http://localhost:3000/api/mes-voyages/42

###

http://{{baseurl}}/api/mesvoyages/monvoyage/1