// mapping filters with OSM keywords
const available_filters = {
        'food': ['amenity=restaurant',
                'amenity=fast_food',
                'amenity=food_court',
                'amenity=cafe',
        ],
        'pub': ['amenity=pub',
                'amenity=biergarten',
                'amenity=bar',
        ],
        'aquatic': ['leisure=sauna',
                'leisure=beach_resort',
                'leisure=swimming_pool',
                'leisure=water_park',
                'sport=water_ski',
                'sport=wakeboarding',
                'amenity=public_bath',
        ],
        'historic': ['historic=aqueduct',
                'historic=archaeological_site',
                'historic=building',
                'historic=castle',
                'historic=castle_wall',
                'historic=church',
                'historic=city_gate',
                'historic=monument',
                'historic=ruins',
        ],
        'art': ['tourism=artwork',
                'amenity=arts_centre',
                'tourism=gallery',
                'tourism=museum',
        ],
        'shop': ['shop=gift',
                'shop=books',
                'shop=anime',
                'shop=music',
                'shop=art',
                'shop=antiques',
                'shop=perfumery',
                'shop=herbalist',
                'shop=second_hand',
                'shop=clothes',
                'shop=health_food',
                'shop=farm',
        ],
        'excursion' : ['tourism=viewpoint',
                     'leisure=park',
        ],
        'fun' : ['amenity=casino',
                'amenity=cinema',
                'amenity=nightclub',
                'amenity=planetarium',
                'amenity=theatre',
                'leisure=amusement_arcade',
                'leisure=escape_game',
                'tourism=attraction',
                'tourism=theme_park',
                'leisure=bandstand',
        ]
};

module.exports = {
        available_filters
};